force-app/main/default/objects/Bulky_Collection_Slot__c/Bulky_Collection_Slot__c.object-meta.xml
<CustomObject>
    <description>Holds the dates of the bulky collections</description>
    <label>Bulky Collection Slot</label>
    <nameField>
        <label>Bulky Collection Slot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bulky Collection Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bulky_Collection_Slot__c/fields/Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>Collection_Date__c</fullName>
    <description>Holds the day of the bulky collection</description>
    <label>Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/Bulky_Collections__c.object-meta.xml
<CustomObject>
    <description>Holds a list of dates and cases</description>
    <label>Bulky Collection</label>
    <nameField>
        <displayFormat>Bulky-{00000}</displayFormat>
        <label>Bulky Collections Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulky Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bulky_Collections__c/fields/Bulky_Collection_Slot__c.field-meta.xml
<CustomField>
    <fullName>Bulky_Collection_Slot__c</fullName>
    <label>Bulky Collection Slot</label>
    <referenceTo>Bulky_Collection_Slot__c</referenceTo>
    <relationshipLabel>Bulky Collections</relationshipLabel>
    <relationshipName>Bulky_Collections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/fields/Bulky_Item_1__c.field-meta.xml
<CustomField>
    <fullName>Bulky_Item_1__c</fullName>
    <label>Bulky Item 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bulky_Collection_Items</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/fields/Bulky_Item_2__c.field-meta.xml
<CustomField>
    <fullName>Bulky_Item_2__c</fullName>
    <label>Bulky Item 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bulky_Collection_Items</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/fields/Bulky_Item_3__c.field-meta.xml
<CustomField>
    <fullName>Bulky_Item_3__c</fullName>
    <label>Bulky Item 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bulky_Collection_Items</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/fields/Bulky_Item_4__c.field-meta.xml
<CustomField>
    <fullName>Bulky_Item_4__c</fullName>
    <label>Bulky Item 4</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bulky_Collection_Items</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/fields/Bulky_Items_Other__c.field-meta.xml
<CustomField>
    <fullName>Bulky_Items_Other__c</fullName>
    <label>Bulky Items_Other</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Bulky Collections</relationshipLabel>
    <relationshipName>Bulky_Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/fields/Where_Items_Left__c.field-meta.xml
<CustomField>
    <fullName>Where_Items_Left__c</fullName>
    <label>Where Items Left</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Front of property on pavement</fullName>
            </value>
            <value>
                <fullName>Front Garden</fullName>
            </value>
            <value>
                <fullName>Rear Garden with free access</fullName>
            </value>
            <value>
                <fullName>Rear Garden with gate access</fullName>
            </value>
            <value>
                <fullName>Side Alleyway</fullName>
            </value>
            <value>
                <fullName>On Driveway</fullName>
            </value>
            <value>
                <fullName>Communal Area</fullName>
            </value>
            <value>
                <fullName>Assisted</fullName>
                <label>I need an Assisted Collection</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Case_Tracking__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Determines if case tracking is one (e.g. mobile and emails to customer)</inlineHelpText>
    <label>Case Tracking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Tracking_Email__c.field-meta.xml
<CustomField>
    <fullName>Case_Tracking_Email__c</fullName>
    <label>Case Tracking Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Tracking_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Case_Tracking_Mobile__c</fullName>
    <label>Case Tracking Mobile</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Bulky_Collection_Items.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>--Please select--</fullName>
    </customValue>
    <customValue>
        <fullName>Armchair</fullName>
    </customValue>
    <customValue>
        <fullName>Bag of Household Waste</fullName>
        <label>Bag of Household Waste (up to 2 bags)</label>
    </customValue>
    <customValue>
        <fullName>Bath</fullName>
    </customValue>
    <customValue>
        <fullName>Bed base only (double)</fullName>
    </customValue>
    <customValue>
        <fullName>Bed base only (single)</fullName>
    </customValue>
    <customValue>
        <fullName>Bed, base, headboard and mattress (double)</fullName>
    </customValue>
    <customValue>
        <fullName>Bed, base, headboard and mattress (single)</fullName>
    </customValue>
    <customValue>
        <fullName>Bedside Cabinet</fullName>
    </customValue>
    <customValue>
        <fullName>Bicycle/Bike</fullName>
    </customValue>
    <customValue>
        <fullName>Blind</fullName>
    </customValue>
    <customValue>
        <fullName>Bookcase</fullName>
    </customValue>
    <customValue>
        <fullName>Bundle of Wood</fullName>
    </customValue>
    <customValue>
        <fullName>Cardboard</fullName>
    </customValue>
    <customValue>
        <fullName>Carpet</fullName>
    </customValue>
    <customValue>
        <fullName>Carpet Gripper Rods</fullName>
    </customValue>
    <customValue>
        <fullName>Chest of drawers</fullName>
    </customValue>
    <customValue>
        <fullName>Child&#39;s Plastic Playhouse</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee Table</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Monitor/Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Tower/Base</fullName>
    </customValue>
    <customValue>
        <fullName>Curtains</fullName>
    </customValue>
    <customValue>
        <fullName>Desk</fullName>
    </customValue>
    <customValue>
        <fullName>Dining Chair</fullName>
    </customValue>
    <customValue>
        <fullName>Dining Table</fullName>
    </customValue>
    <customValue>
        <fullName>Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Door - Internal</fullName>
    </customValue>
    <customValue>
        <fullName>Dressing Table</fullName>
    </customValue>
    <customValue>
        <fullName>Fence Panel - Broken</fullName>
    </customValue>
    <customValue>
        <fullName>Fence Panel - Undamaged</fullName>
    </customValue>
    <masterLabel>Bulky Collection Items</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RCCBulkyController_Test.cls
@isTest
public class RCCBulkyController_Test {

    
    @isTest static void testGetBulkyDateOptions() {
        
        
        Date d = Date.parse('12/12/2018');
        // create a case
        Bulky_Collection_Slot__c Bulkyslot = new Bulky_Collection_Slot__c(
          Name = '12th December 2018',  
    	  Collection_Date__c = d
        );
		insert Bulkyslot;
        
        
        List<Bulky_Collection_Slot__c> bulkyDates = RCCBulkyController.GetBulkyDateOptions();
        
        
        Account address = new Account(
            Name = 'test address'
        );
        insert address;
        
        Case caseObj = new Case(
          Description = 'Test Case',  
    	  Status = 'Working',
    	  Origin = 'Phone',
          Case_Tracking__c  = true,
          Case_Tracking_Email__c = 'andynuk@gmail.com', 
          Case_Tracking_Mobile__c = '07398 251287'
        );
		insert caseObj;
        
        
        Bulky_Collections__c bulky = new Bulky_Collections__c(
        Where_Items_Left__c = 'Front Garden', 
        Bulky_Item_1__c ='Bath',
        Bulky_Item_2__c ='Bath',
        Bulky_Item_3__c ='Bath',
        Bulky_Item_4__c ='Bath',
        Bulky_Items_Other__c ='Bath',
        Case__c = caseObj.Id,
        Bulky_Collection_Slot__c = Bulkyslot.Id
        );    
        insert bulky;
        
        List<Bulky_Collections__c> test1= RCCBulkyController.GetBulkyHistory(address.Id);
        
        List<Bulky_Collections__c> test2 = RCCBulkyController.GetBulkyReminder(bulky.Id);
        
        //RCCBulkyController.sendBulkyReminder(bulky.Id);
        
     }
}