force-app/main/default/objects/Bulky_Collection_Slot__c/Bulky_Collection_Slot__c.object-meta.xml
<CustomObject>
    <description>Holds the dates of the bulky collections</description>
    <label>Bulky Collection Slot</label>
    <nameField>
        <label>Bulky Collection Slot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bulky Collection Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bulky_Collection_Slot__c/fields/Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>Collection_Date__c</fullName>
    <description>Holds the day of the bulky collection</description>
    <label>Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bulky_Collection_Slot__c/fields/Maximum_Assisted_Collections__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Assisted_Collections__c</fullName>
    <defaultValue>2</defaultValue>
    <label>Maximum Assisted Collections</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bulky_Collection_Slot__c/fields/Maximum_Normal_Collections__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Normal_Collections__c</fullName>
    <defaultValue>28</defaultValue>
    <label>Maximum Normal Collections</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bulky_Collection_Slot__c/fields/Number_of_Assisted_Visits__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Assisted_Visits__c</fullName>
    <label>Number of Assisted Visits</label>
    <summaryFilterItems>
        <field>Bulky_Collections__c.Assisted_Collection__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Bulky_Collections__c.Bulky_Collection_Slot__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Bulky_Collection_Slot__c/fields/Number_of_Filled_Slots__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Filled_Slots__c</fullName>
    <description>Shows number of filled slots for this date</description>
    <inlineHelpText>Shows number of filled slots for this date</inlineHelpText>
    <label>Number of Visits</label>
    <summaryForeignKey>Bulky_Collections__c.Bulky_Collection_Slot__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/Bulky_Collections__c.object-meta.xml
<CustomObject>
    <description>Holds a list of dates and cases</description>
    <label>Bulky Collection</label>
    <nameField>
        <displayFormat>Bulky-{00000}</displayFormat>
        <label>Bulky Collections Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulky Collections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bulky_Collections__c/fields/Bulky_Collection_Slot__c.field-meta.xml
<CustomField>
    <fullName>Bulky_Collection_Slot__c</fullName>
    <label>Bulky Collection Slot</label>
    <referenceTo>Bulky_Collection_Slot__c</referenceTo>
    <relationshipLabel>Bulky Collections</relationshipLabel>
    <relationshipName>Bulky_Collections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/fields/Bulky_Item_1__c.field-meta.xml
<CustomField>
    <fullName>Bulky_Item_1__c</fullName>
    <label>Bulky Item 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bulky_Collection_Items</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/fields/Bulky_Item_2__c.field-meta.xml
<CustomField>
    <fullName>Bulky_Item_2__c</fullName>
    <label>Bulky Item 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bulky_Collection_Items</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/fields/Bulky_Item_3__c.field-meta.xml
<CustomField>
    <fullName>Bulky_Item_3__c</fullName>
    <label>Bulky Item 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bulky_Collection_Items</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/fields/Bulky_Item_4__c.field-meta.xml
<CustomField>
    <fullName>Bulky_Item_4__c</fullName>
    <label>Bulky Item 4</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bulky_Collection_Items</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/fields/Bulky_Items_Other__c.field-meta.xml
<CustomField>
    <fullName>Bulky_Items_Other__c</fullName>
    <label>Bulky Items_Other</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Bulky Collections</relationshipLabel>
    <relationshipName>Bulky_Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/fields/Internal_Waste_Team_Notes__c.field-meta.xml
<CustomField>
    <fullName>Internal_Waste_Team_Notes__c</fullName>
    <label>Internal Waste Team Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Bulky_Collections__c/fields/Where_Items_Left__c.field-meta.xml
<CustomField>
    <fullName>Where_Items_Left__c</fullName>
    <label>Where Items Left</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Front of property on pavement</fullName>
            </value>
            <value>
                <fullName>Front Garden</fullName>
            </value>
            <value>
                <fullName>Rear Garden with free access</fullName>
            </value>
            <value>
                <fullName>Rear Garden with gate access</fullName>
            </value>
            <value>
                <fullName>Side Alleyway</fullName>
            </value>
            <value>
                <fullName>On Driveway</fullName>
            </value>
            <value>
                <fullName>Communal Area</fullName>
            </value>
            <value>
                <fullName>Assisted</fullName>
                <label>I need an Assisted Collection</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Case_Tracking__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Determines if case tracking is one (e.g. mobile and emails to customer)</inlineHelpText>
    <label>Case Tracking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Tracking_Email__c.field-meta.xml
<CustomField>
    <fullName>Case_Tracking_Email__c</fullName>
    <label>Case Tracking Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Tracking_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Case_Tracking_Mobile__c</fullName>
    <label>Case Tracking Mobile</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Bulky_Collection_Items.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>--Please select--</fullName>
    </customValue>
    <customValue>
        <fullName>Armchair</fullName>
    </customValue>
    <customValue>
        <fullName>Bag of Household Waste</fullName>
        <label>Bag of Household Waste (up to 2 bags)</label>
    </customValue>
    <customValue>
        <fullName>Bath</fullName>
    </customValue>
    <customValue>
        <fullName>Bed base only (double)</fullName>
    </customValue>
    <customValue>
        <fullName>Bed base only (single)</fullName>
    </customValue>
    <customValue>
        <fullName>Bed, base, headboard and mattress (double)</fullName>
    </customValue>
    <customValue>
        <fullName>Bed, base, headboard and mattress (single)</fullName>
    </customValue>
    <customValue>
        <fullName>Bedside Cabinet</fullName>
    </customValue>
    <customValue>
        <fullName>Bicycle/Bike</fullName>
    </customValue>
    <customValue>
        <fullName>Blind</fullName>
    </customValue>
    <customValue>
        <fullName>Bookcase</fullName>
    </customValue>
    <customValue>
        <fullName>Bundle of Wood</fullName>
    </customValue>
    <customValue>
        <fullName>Cardboard</fullName>
    </customValue>
    <customValue>
        <fullName>Carpet</fullName>
    </customValue>
    <customValue>
        <fullName>Carpet Gripper Rods</fullName>
    </customValue>
    <customValue>
        <fullName>Chest of drawers</fullName>
    </customValue>
    <customValue>
        <fullName>Child&#39;s Plastic Playhouse</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee Table</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Monitor/Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Tower/Base</fullName>
    </customValue>
    <customValue>
        <fullName>Curtains</fullName>
    </customValue>
    <customValue>
        <fullName>Desk</fullName>
    </customValue>
    <customValue>
        <fullName>Dining Chair</fullName>
    </customValue>
    <customValue>
        <fullName>Dining Table</fullName>
    </customValue>
    <customValue>
        <fullName>Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Door - Internal</fullName>
    </customValue>
    <customValue>
        <fullName>Dressing Table</fullName>
    </customValue>
    <customValue>
        <fullName>Fence Panel - Broken</fullName>
    </customValue>
    <customValue>
        <fullName>Fence Panel - Undamaged</fullName>
    </customValue>
    <masterLabel>Bulky Collection Items</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RCCBulkyController.cls
public class RCCBulkyController {

    @AuraEnabled
    public static List<Bulky_Collection_Slot__c> GetBulkyDateOptions() {
        /* This call returns all the future bulky collection dates
         * Bulky_Collection_Slot__c is custom table with date information
        */
        List<Bulky_Collection_Slot__c> bulkyDates;
        bulkyDates = [SELECT id, Name, Collection_Date__c,Number_of_Assisted_Visits__c,Number_of_Filled_Slots__c,Maximum_Normal_Collections__c,Maximum_Assisted_Collections__c FROM Bulky_Collection_Slot__c WHERE Collection_Date__c > TODAY ORDER BY Collection_Date__c ASC LIMIT 10];
        return bulkyDates;
    }
    
    @AuraEnabled
    public static List<Bulky_Collections__c> GetBulkyHistory(Id AddressId) {
        List<Bulky_Collections__c> bulkyDates;
        bulkyDates = [SELECT id, Name, Case__r.Account.Id, Case__r.CaseNumber, Bulky_Collection_Slot__r.Collection_Date__c FROM Bulky_Collections__c WHERE Case__r.Account.Id=: AddressId order by Bulky_Collection_Slot__r.Collection_Date__c DESC];
            
        return bulkyDates;
    }
    
    @AuraEnabled
    public static List<Bulky_Collections__c> GetBulkyReminder(Id BulkyId) {
        List<Bulky_Collections__c> bulkyInfo;
        bulkyInfo = [SELECT id, Name, Where_Items_Left__c, Bulky_Item_1__c,Bulky_Item_2__c,Bulky_Item_3__c,Bulky_Item_4__c,Bulky_Items_Other__c ,Internal_Waste_Team_Notes__c ,Case__r.CaseNumber, Case__r.Case_Tracking__c,Case__r.Case_Tracking_Email__c , Case__r.Case_Tracking_Mobile__c, Bulky_Collection_Slot__r.Name FROM Bulky_Collections__c WHERE Id=: BulkyId];
            
        return bulkyInfo;
    }
    
    
    @AuraEnabled
    public static void sendBulkyReminder(Id BulkyId) {
        List<Bulky_Collections__c> bulkyInfo = GetBulkyReminder(BulkyId);
        
        string message;
        
        if (bulkyInfo[0].Case__r.Case_Tracking__c)
           {

              // test for mobile
              if (bulkyInfo[0].Case__r.Case_Tracking_Mobile__c == null)
              {
              }
               else
              {
			       system.debug('Sending SMS');
                  message ='This is a reminder of your Bulky Collection on '+bulkyInfo[0].Bulky_Collection_Slot__r.Name+'.';
                  if (bulkyInfo[0].Where_Items_Left__c == 'Assisted')
                  {
                      message = message + 'You have an assisted Collection.';
                  }
                  else
                  {
                      message = message + 'Please put your items in the '+bulkyInfo[0].Where_Items_Left__c;
                  }                      
                  System.enqueueJob(new caseTrackingClass.sendSMSMessage(message, bulkyInfo[0].Case__r.Case_Tracking_Mobile__c));
              }
              if (bulkyInfo[0].Case__r.Case_Tracking_Email__c == null)
              {
              }
              else
              {
			       system.debug('Sending Email');
                  message ='<p>You have arranged a Bulky Collection on '+bulkyInfo[0].Bulky_Collection_Slot__r.Name+'.</p>';
                  message = message + '<p>We will collect the following items</p>';
                  if (bulkyInfo[0].Bulky_Item_1__c != null)
                  	 { message = message + '<p>'+bulkyInfo[0].Bulky_Item_1__c+'</p>';}
                  if (bulkyInfo[0].Bulky_Item_2__c != null)
                 	 { message = message + '<p>'+bulkyInfo[0].Bulky_Item_2__c+'</p>';}
                  if (bulkyInfo[0].Bulky_Item_3__c != null)
                 	 { message = message + '<p>'+bulkyInfo[0].Bulky_Item_3__c+'</p>';}
                  if (bulkyInfo[0].Bulky_Item_4__c != null)
                 	 { message = message + '<p>'+bulkyInfo[0].Bulky_Item_4__c+'</p>';}                  
                  if (bulkyInfo[0].Where_Items_Left__c == 'Assisted')
                  {
                      message = message + '<p>You have an assisted Collection and we will ensure that your items are safely collected from your property.';
                  }
                  else
                  {
                      message = message + '<p>Please put your items in the '+bulkyInfo[0].Where_Items_Left__c;
                  } 
                  message = message + '<p>If you would like to discuss this please call our customer service centre on 01572 722 577.</p>';
                  message = message + '<p>Please quote case reference '+bulkyInfo[0].Case__r.CaseNumber+'</p>';
                  
                  caseTrackingClass.sendEmailMessage('Rutland County Council - Bulky Collection Reminder',message, bulkyInfo[0].Case__r.Case_Tracking_Email__c);
              }
               
           }
       
       

    }}